### ISSUE TITLE
CodeScannerView layout displaying black screen after use of scanner many times.

### ISSUE THREAD

**Issue by marcfrancislargo** [yuriy-budiyev/code-scanner#131]
Im using this code on my example app on its oncreate mainactivity:
```
CodeScannerView scannerView = findViewById(R.id.scanner_view);
        mCodeScanner = new CodeScanner(this, scannerView);
        mCodeScanner.setDecodeCallback(new DecodeCallback() {
            @Override
            public void onDecoded(@NonNull final Result result) {
                runOnUiThread(new Runnable() {
                    public void run() {
                        final Toast toast = Toast.makeText(MainActivity.this, result.getText(), Toast.LENGTH_SHORT);
                        toast.show();
                    }
                });
            }
        });
        scannerView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                mCodeScanner.startPreview();
            }
        });
```

at like first 5 times its working fine but after, it just displays black screen then crashes. (opening the app, clearing it from the recents for multiple times, thats what i mean).

```
Process: com.example.app, PID: 3733
    java.lang.RuntimeException: Fail to connect to camera service
        at android.hardware.Camera.<init>(Camera.java:643)
        at android.hardware.Camera.open(Camera.java:464)
        at com.budiyev.android.codescanner.CodeScanner$InitializationThread.initialize(CodeScanner.java:835)
        at com.budiyev.android.codescanner.CodeScanner$InitializationThread.run(CodeScanner.java:812)
```

i've read that you need to reclaim the camera to be able to use it again even if you already allowed the needed permission.

**Comment by prachi1199** [comment]
Did you find a permanent fix for this?
