### ISSUE TITLE
Unknown camera crash

### ISSUE THREAD

**Issue by hassanalinali** [yuriy-budiyev/code-scanner#14]
On a Huawei test device with Android 6.0(M) the activity with the code scanner view just consistently crashes with this unknown camera error. Is there anything that we can do?

Unknown camera error(-1)
java.lang.RuntimeException: Unknown camera error(-1)
at android.hardware.Camera.<init>(Camera.java:593)
at android.hardware.Camera.open(Camera.java:414)
at com.budiyev.android.codescanner.CodeScanner$InitializationThread.initialize(CodeScanner.java:736)
at com.budiyev.android.codescanner.CodeScanner$InitializationThread.run(CodeScanner.java:713)

**Comment by vcoolish** [comment]
how did you solve it?

**Comment by Mahmoudak** [comment]
where is the solution
