### ISSUE TITLE
ANR at DecoderWrapper.java line 107

### ISSUE THREAD

**Issue by Zookey** [yuriy-budiyev/code-scanner#161]
Hi,

I am using the library and it works great, but I see some ANR reports in Firebase Crashlytics.

One of the is at DecoderWrapper.java line 107.

This is full log that I have:

`main (native): tid=1 systid=25398 
#00 pc 0x9aec4 libc.so 
#01 pc 0x57ca0 libc.so 
#02 pc 0x519e4 libbinder.so 
#03 pc 0x529e0 libbinder.so 
#04 pc 0x52750 libbinder.so 
#05 pc 0x4b014 libbinder.so 
#06 pc 0x52124 libcamera_client.so 
#07 pc 0x45bac libcamera_client.so 
#08 pc 0x1464e0 libandroid_runtime.so 
       at android.hardware.Camera.native_release(Native method)
       at android.hardware.Camera.release(Camera.java:659)
       at com.budiyev.android.codescanner.DecoderWrapper.release(DecoderWrapper.java:107)
       at com.budiyev.android.codescanner.CodeScanner.releaseResourcesInternal(CodeScanner.java:625)
       at com.budiyev.android.codescanner.CodeScanner.releaseResources(CodeScanner.java:483)
       at com.anstar.fieldworkhq.workorders.ScanDeviceActivity.onDestroy(ScanDeviceActivity.java:69)
       at android.app.Activity.performDestroy(Activity.java:8355)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1344)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5193)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5240)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2130)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:250)
       at android.app.ActivityThread.main(ActivityThread.java:7803)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)`

Is it possible to fix this?

**Comment by yuriy-budiyev** [comment]
It's in camera:
       at android.hardware.Camera._stopPreview(Native method)
       at android.hardware.Camera.stopPreview(Camera.java:775)

**Comment by yuriy-budiyev** [comment]
DecoderWrapper works at background thread ANR isn't possible there.

**Comment by Zookey** [comment]
@yuriy-budiyev So, it seems that is the issue in Android Camera, right?

**Comment by Zookey** [comment]
@yuriy-budiyev I still facing this issue, for example in last 30 days, I had 19 ANR on  those two lines:

`#06 pc 0x1cd354 libandroid_runtime.so (android_hardware_Camera_getParameters + 68) (BuildId: b0893a6825cde6461399fdbd80011e2f)
       at android.hardware.Camera.native_getParameters(Native method)
       at android.hardware.Camera.getParameters(Camera.java:2058)
       at com.budiyev.android.codescanner.CodeScanner.stopPreviewInternal(CodeScanner.java:599)
       at com.budiyev.android.codescanner.CodeScanner.stopPreview(CodeScanner.java:472)
       at com.budiyev.android.codescanner.CodeScanner.releaseResources(CodeScanner.java:483)
       at com.mobile.test.workorders.devices.ScanDeviceActivity.onPause(ScanDeviceActivity.java:69)`

or 

`#06 pc 0x206830 libandroid_runtime.so (android_hardware_Camera_release + 272) (BuildId: 4cb6e99ade538eb484020188e9672508)
       at android.hardware.Camera.native_release(Native method)
       at android.hardware.Camera.release(Camera.java:675)
       at com.budiyev.android.codescanner.DecoderWrapper.release(DecoderWrapper.java:107)
       at com.budiyev.android.codescanner.CodeScanner.releaseResourcesInternal(CodeScanner.java:630)
       at com.budiyev.android.codescanner.CodeScanner.releaseResources(CodeScanner.java:485)
       at com.mobile.test.workorders.devices.ScanDeviceActivity.onPause(ScanDeviceActivity.java:69)`


In in my code I just call thia:

  @Override protected void onPause() {
    super.onPause();
    codeScanner.releaseResources();
  }

So, this ANR is trigerred in this onPause where the code canner tries to release resources.

Do you have any ideas?
