### ISSUE TITLE
setParameters failed

### ISSUE THREAD

**Issue by ProstoF** [yuriy-budiyev/code-scanner#64]
Hello! 
I have a few crashes in Crashlytics with this error:

```
Fatal Exception: java.lang.RuntimeException: setParameters failed
       at android.hardware.Camera.native_setParameters(Camera.java)
       at android.hardware.Camera.setParameters(Camera.java:2045)
       at com.budiyev.android.codescanner.CodeScanner$InitializationThread.initialize(CodeScanner.java:891)
       at com.budiyev.android.codescanner.CodeScanner$InitializationThread.run(CodeScanner.java:812)
```

As I understand we request the camera to be with the view's sizes, but the camera does not support such sizes: https://stackoverflow.com/a/33580027/2838676

Devices: Xiaomi Redmi 4X, Samsung Galaxy A5(2017)

**Comment by ProstoF** [comment]
I found a code that selects the correct preview size in Utils.findSuitableImageSize(), I do not know what could be the error

**Comment by krupalbhardiya** [comment]
More exceptions:

`Fatal Exception: java.lang.RuntimeException: getParameters failed (empty parameters)
       at android.hardware.Camera.native_getParameters(Camera.java)
       at android.hardware.Camera.getParameters(Camera.java:1960)
       at com.budiyev.android.codescanner.CodeScanner$InitializationThread.initialize(CodeScanner.java:66)
       at com.budiyev.android.codescanner.CodeScanner$InitializationThread.run(CodeScanner.java:5)`

Device: Samsung Galaxy J7 Max

**Comment by yuriy-budiyev** [comment]
This is really wired. I need as much info as possible.

**Comment by krupalbhardiya** [comment]
This is all the info i have. All gathered from crashlytics.

**Comment by yuriy-budiyev** [comment]
How do you use CodeScanner? Layout file? The source code?

**Comment by ProstoF** [comment]
One user noticed that if you first open the camera (standard application), and then the camera in my application, then everything is fine, but if immediately in my application, a black screen appears.
I do not know how much it can help, I still can not reproduce this error.

I use CodeScanner in a fragment.
onCreateView:
```
CodeScannerView codeScannerView = view.findViewById(R.id.codeScannerView);

mCodeScanner = new CodeScanner(mainActivity, codeScannerView);
mCodeScanner.setFormats(Arrays.asList(BarcodeFormat.QR_CODE));
mCodeScanner.setDecodeCallback(new DecodeCallback() {
    @Override
    public void onDecoded(@NonNull com.google.zxing.Result result) {
        mainActivity.runOnUiThread(new Runnable() {
            @Override
            public void run() {
                ....
            }
        });
    }
});
```
and onResume, onPause
```
@Override
public void onResume() {
    super.onResume();

   // ask about permission before start preview
    Dexter.withActivity(mainActivity)
            .withPermission(Manifest.permission.CAMERA)
            .withListener(new PermissionListener() {
                @Override public void onPermissionGranted(PermissionGrantedResponse response) {
                    mCodeScanner.startPreview();
                }
                @Override public void onPermissionDenied(PermissionDeniedResponse response) {
                    // permission denied
                }
                @Override public void onPermissionRationaleShouldBeShown(PermissionRequest permission, final PermissionToken token) {
                    // ask
                }
            })
            .onSameThread()
            .check();
}

@Override
public void onPause() {
    super.onPause();
    mCodeScanner.releaseResources();
}
```


layout: 
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical">

    <androidx.swiperefreshlayout.widget.SwipeRefreshLayout
        android:id="@+id/swipeRefreshLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.budiyev.android.codescanner.CodeScannerView
            android:id="@+id/codeScannerView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:autoFocusButtonColor="@android:color/white"
            app:autoFocusButtonVisible="false"
            app:flashButtonColor="@android:color/white"
            app:flashButtonVisible="false"
            app:frameColor="@android:color/white"
            app:frameCornersSize="50dp"
            app:frameCornersRadius="0dp"
            app:frameAspectRatioWidth="1"
            app:frameAspectRatioHeight="1"
            app:frameSize="0.75"
            app:frameThickness="2dp"
            app:maskColor="#77000000"/>

    </androidx.swiperefreshlayout.widget.SwipeRefreshLayout>

</LinearLayout>
```

**Comment by yuriy-budiyev** [comment]
Maybe, threre are bugs in Camera API on target devices.
Probably, in future versions, ill update to Camera2 API. When API levels lower 21 become irrelevant.

**Comment by princeivankent** [comment]
Does anyone solve this problem? I'm facing the same issue on our crashlytics. Thanks!
