### ISSUE TITLE
 java.lang.NoSuchMethodError: java.util.List.sort

### ISSUE THREAD

**Issue by anjanaps** [yuriy-budiyev/code-scanner#74]
I am getting this issue , how to solve this 
java.lang.NoSuchMethodError: java.util.List.sort
        at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:616)
        at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:164)
        at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)
        at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
        at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:173)
        at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:87)
        at com.budiyev.android.codescanner.Utils.decodeLuminanceSource(Utils.java:342)
        at com.budiyev.android.codescanner.DecodeTask.decode(DecodeTask.java:75)
        at com.budiyev.android.codescanner.Decoder$DecoderThread.run(Decoder.java:133)

**Comment by yuriy-budiyev** [comment]
This method was added in Java 8. Have you changed ZXing dependancy version manually?
