### ISSUE TITLE
Failed to connect to Camera Service

### ISSUE THREAD

**Issue by himgupta229** [yuriy-budiyev/code-scanner#80]
Hi,
I am using library version 2.1.0 and on Xiaomi device(Os 5.1.1) I am always getting below exception:

Fatal Exception: java.lang.RuntimeException: Fail to connect to camera service
       at android.hardware.Camera.<init> + 533(Camera.java:533)
       at android.hardware.Camera.open + 365(Camera.java:365)
       at com.budiyev.android.codescanner.CodeScanner$InitializationThread.initialize + 835(CodeScanner.java:835)
       at com.budiyev.android.codescanner.CodeScanner$InitializationThread.run + 812(CodeScanner.java:812)

**Comment by zzzzzzzzoli** [comment]
Hi,
I am also using library version 2.1.0 and have the same crash with a Xiaomi Redmi K20 (Android 10):

Fatal Exception: java.lang.RuntimeException: Fail to connect to camera service
       at android.hardware.Camera.<init>(Camera.java:637)
       at android.hardware.Camera.open(Camera.java:458)
       at com.budiyev.android.codescanner.CodeScanner$InitializationThread.initialize(CodeScanner.java:835)
       at com.budiyev.android.codescanner.CodeScanner$InitializationThread.run(CodeScanner.java:812)

**Comment by MrShoxruxbek** [comment]
Hi, I am also using library version 2.1.0 and the same crash with Xiaomi Android version 10

**Comment by MrShoxruxbek** [comment]
> Hi,
> I am using library version 2.1.0 and on Xiaomi device(Os 5.1.1) I am always getting below exception:
> 
> Fatal Exception: java.lang.RuntimeException: Fail to connect to camera service
> at android.hardware.Camera. + 533(Camera.java:533)
> at android.hardware.Camera.open + 365(Camera.java:365)
> at com.budiyev.android.codescanner.CodeScanner$InitializationThread.initialize + 835(CodeScanner.java:835)
> at com.budiyev.android.codescanner.CodeScanner$InitializationThread.run + 812(CodeScanner.java:812)

Because Android 10 not supported.

**Comment by dondell** [comment]
I have the same issue
`Fatal Exception: java.lang.RuntimeException: Fail to connect to camera service
       at android.hardware.Camera.<init>(Camera.java:667)
       at android.hardware.Camera.open(Camera.java:503)
       at com.budiyev.android.codescanner.CodeScanner$InitializationThread.initialize(CodeScanner.java:835)
       at com.budiyev.android.codescanner.CodeScanner$InitializationThread.run(CodeScanner.java:812)`

**Comment by YasinEnu** [comment]
Facing the same issue, the problem occurs when I try to initialize the camera the second time in a row, 

W: An error occurred while connecting to camera: 0
W: java.lang.RuntimeException: Fail to connect to camera service
W:     at android.hardware.Camera.<init>(Camera.java:550)
W:     at android.hardware.Camera.open(Camera.java:390)
W:     at com.budiyev.android.codescanner.CodeScanner$InitializationThread.initialize(CodeScanner.java:835)
W:     at com.budiyev.android.codescanner.CodeScanner$InitializationThread.run(CodeScanner.java:812)
D: Camera initialization error: Fail to connect to camera service

**Comment by YasinEnu** [comment]
> I have the same issue
> `Fatal Exception: java.lang.RuntimeException: Fail to connect to camera service at android.hardware.Camera.<init>(Camera.java:667) at android.hardware.Camera.open(Camera.java:503) at com.budiyev.android.codescanner.CodeScanner$InitializationThread.initialize(CodeScanner.java:835) at com.budiyev.android.codescanner.CodeScanner$InitializationThread.run(CodeScanner.java:812)`

Did you found any solution yet?

**Comment by dondell** [comment]
I haven't found solution yet.

dondellbatac@gmail.com
+639263821678
Bulacao, Talisay City, Cebu 6045
Skype: dondell.dev

**Comment by shamshadpattani** [comment]
same here

**Comment by michaelbelete** [comment]
the problem is with the mobile no giving camera permission to your app. if you went to setting -> app -> {your app} -> permissions and enabled camera permission it works fine. so i guess you got to ask for permission of camera first

**Comment by PavelLepikhov** [comment]
The library provides a mechanism for intercepting camera initialization errors. To do this, when initializing the CodeScaner, you must set the ErrorCallback using setErrorCallback (final ErrorCallback errorCallback). If an error (any) occurs during initialization, the library checks for the presence of this callback and, if not, throws an error, and if there is, processes it.
```
try {
                initialize();
            } catch (final Exception e) {
                releaseResourcesInternal();
                final ErrorCallback errorCallback = mErrorCallback;
                if (errorCallback != null) {
                    errorCallback.onError(e);
                } else {
                    throw e;
                }
            }
```

**Comment by yuriy-budiyev** [comment]
Check camera permissions and update to 2.1.2 for better error handling.
