### ISSUE TITLE
Getting crash on Android 8.0 

### ISSUE THREAD

**Issue by wegileShashankRawat** [yuriy-budiyev/code-scanner#87]
Hi, 
I am getting crash reports on devices having Android 8.0 version in it. 

The crash details are: 
         Fatal Exception: java.lang.RuntimeException: getParameters failed (empty parameters)
       at android.hardware.Camera.native_getParameters(Camera.java)
       at android.hardware.Camera.getParameters(Camera.java:1910)
       at com.budiyev.android.codescanner.CodeScanner$InitializationThread.initialize(CodeScanner.java:847)
       at com.budiyev.android.codescanner.CodeScanner$InitializationThread.run(CodeScanner.java:812)

**Comment by wegileShashankRawat** [comment]
Also getting this one crash: 

Fatal Exception: java.lang.RuntimeException: set display orientation failed
       at android.hardware.Camera.setDisplayOrientation(Camera.java)
       at com.budiyev.android.codescanner.CodeScanner$InitializationThread.initialize(CodeScanner.java:892)
       at com.budiyev.android.codescanner.CodeScanner$InitializationThread.run(CodeScanner.java:812)

**Comment by dulatello08** [comment]
Same
